import { execFileSync } from 'node:child_process';
import { createHash, randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';
import { createInterface } from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';

const root = process.cwd();
const appDir = `${root}/my-sonicjs-app`;
const configPath = `${appDir}/wrangler.production.toml`;
const npx = process.platform === 'win32' ? 'npx.cmd' : 'npx';

const run = (args, opts = {}) => {
  console.log(`\n> npx ${args.join(' ')}`);
  return execFileSync(npx, args, { cwd: root, stdio: 'inherit', shell: false, ...opts });
};

const runText = (args) => execFileSync(npx, args, { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], shell: false });

const rl = createInterface({ input, output });
const ask = async (question, fallback = '') => {
  const answer = (await rl.question(`${question}${fallback ? ` [${fallback}]` : ''}: `)).trim();
  return answer || fallback;
};

try {
  console.log('=== SonicJS Cloudflare Production Setup ===');
  console.log('This script does not create or store an admin password.');
  console.log('It uses your Cloudflare login and your existing D1 database.');

  try { run(['wrangler', 'whoami']); }
  catch {
    console.log('\nCloudflare login is required. A browser window will open.');
    run(['wrangler', 'login']);
  }

  const workerName = (await ask('Worker name', 'szfp8-tax-seo')).replace(/[^a-zA-Z0-9-]/g, '-');
  const domainInput = await ask('Custom domain(s), comma separated', 'szfp8.com');
  const domains = domainInput.split(',').map((v) => v.trim().toLowerCase().replace(/^https?:\/\//, '').replace(/\/$/, '')).filter(Boolean);
  if (!domains.length) throw new Error('At least one domain is required.');

  const d1Name = await ask('Existing D1 database name');
  let d1Id = '';
  if (d1Name) {
    try {
      const raw = runText(['wrangler', 'd1', 'info', d1Name, '--json']);
      const info = JSON.parse(raw);
      d1Id = info.uuid || info.id || info.database_id || info.databaseId || '';
    } catch {
      console.log('Could not read D1 by name.');
    }
  }
  if (!d1Id) d1Id = await ask('D1 database ID');
  if (!d1Id) throw new Error('D1 database ID is required.');

  const siteName = await ask('Site name', 'National Tax & Invoice Service');
  const phone = await ask('Contact phone (optional)', '');
  const firstUrl = `https://${domains[0]}`;
  const indexNowKey = createHash('sha256').update(randomBytes(24)).digest('hex').slice(0, 32);

  const routeBlock = domains.map((domain) => `[[routes]]\npattern = "${domain}"\ncustom_domain = true`).join('\n\n');
  const config = `# Generated by scripts/cloudflare/setup.mjs. Do not commit this file.\nname = "${workerName}"\nmain = "src/index.ts"\ncompatibility_date = "2026-09-01"\ncompatibility_flags = ["nodejs_compat"]\nworkers_dev = true\n\n[[d1_databases]]\nbinding = "DB"\ndatabase_name = "${d1Name || 'existing-d1'}"\ndatabase_id = "${d1Id}"\nmigrations_dir = "./migrations"\n\n[vars]\nENVIRONMENT = "production"\nSITE_NAME = "${siteName.replaceAll('"', '\\"')}"\nSITE_URL = "${firstUrl}"\nCONTACT_PHONE = "${phone.replaceAll('"', '\\"')}"\n\n${routeBlock}\n\n[triggers]\ncrons = ["0 */6 * * *"]\n\n[observability]\nenabled = true\n`;

  writeFileSync(configPath, config, 'utf8');
  console.log(`\nGenerated ${configPath}`);

  if (!existsSync(`${root}/node_modules`)) run(['install']);
  run(['run', 'build:core']);
  run(['wrangler', 'd1', 'migrations', 'apply', 'DB', '--remote', '--config', configPath]);

  console.log('\nSetting an IndexNow secret (optional SEO notification).');
  try {
    execFileSync(npx, ['wrangler', 'secret', 'put', 'INDEXNOW_KEY', '--config', configPath], {
      cwd: root, input: `${indexNowKey}\n`, stdio: ['pipe', 'inherit', 'inherit'], shell: false,
    });
  } catch {
    console.log('IndexNow secret was not set; deployment will still continue.');
  }

  run(['wrangler', 'deploy', '--config', configPath]);
  console.log('\n=== DEPLOY COMPLETE ===');
  console.log(`Site: ${firstUrl}`);
  console.log(`Worker: ${workerName}`);
  console.log('Admin login: use SonicJS first-run/admin setup; no password was hard-coded.');
  console.log('SEO endpoints: /robots.txt  /sitemap.xml  /news  /contact');
  console.log('City pages: /city/<city-name>');
} catch (error) {
  console.error('\nDEPLOY FAILED');
  console.error(error?.message || error);
  process.exitCode = 1;
} finally {
  await rl.close();
}
