/**
 * Beginner-friendly Chinese admin shell — 财税 SEO + AI关键词 + GEO
 */
const MARKER = 'data-tax-seo-beginner-ui';
const script = `<script ${MARKER}>
(function () {
  if (window.__taxSeoBeginnerAdmin) return;
  window.__taxSeoBeginnerAdmin = true;
  var menu = [
    { text: '数据概览', href: '/admin', icon: '📊' },
    { text: '内容管理', href: '/admin/content', icon: '📝' },
    { text: '文章管理', href: '/admin/content?model=seo_article', icon: '📰' },
    { text: '城市管理', href: '/admin/content?model=seo_city_page', icon: '📍' },
    { text: '微信文章', href: '/admin/content?model=wechat_article', icon: '💬' },
    { text: 'SEO设置', href: '/admin/settings/general#seo', icon: '🔎' },
    { text: 'AI关键词', href: '/admin/settings/general#ai-seo', icon: '🤖' },
    { text: 'GEO设置', href: '/admin/settings/general#geo', icon: '🌐' },
    { text: '获客设置', href: '/admin/settings/general#lead', icon: '☎' },
    { text: '首页设置', href: '/admin/settings/general#home', icon: '🏠' },
    { text: '客户管理', href: '/admin/users', icon: '👤' },
    { text: '系统设置', href: '/admin/settings/general', icon: '⚙' }
  ];
  function cleanText(v){return (v||'').replace(/\\s+/g,' ').trim();}
  function findText(text){var w=cleanText(text),all=document.querySelectorAll('a,button,span,div,p,h1,h2,h3,label');for(var i=0;i<all.length;i++)if(cleanText(all[i].textContent)===w)return all[i];return null;}
  function setText(a,b){var el=findText(a);if(el&&cleanText(el.textContent)!==cleanText(b))el.textContent=b;}
  function esc(v){return String(v==null?'':v).replace(/[&<>\\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;',"'":'&#39;'}[c];});}
  function addStyles(){if(document.getElementById('tax-seo-beginner-style'))return;var s=document.createElement('style');s.id='tax-seo-beginner-style';s.textContent='nav[class*="bg-"]{background:#0f172a!important}[data-tax-seo-shell]{margin:0 0 18px}.tax-seo-brand{display:flex;align-items:center;gap:12px;padding:16px;border-radius:14px;background:linear-gradient(135deg,#1e3a8a,#2563eb);color:#fff}.tax-seo-brand-icon{width:40px;height:40px;display:flex;align-items:center;justify-content:center;border-radius:10px;background:rgba(255,255,255,.16);font-weight:800}.tax-seo-brand-title{font-size:17px;font-weight:700}.tax-seo-brand-sub{margin-top:3px;font-size:12px;opacity:.82}.tax-seo-quick{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px;margin-top:12px}.tax-seo-quick a{display:block;padding:14px;border:1px solid #e5e7eb;border-radius:12px;background:#fff;color:#172033;text-decoration:none}.tax-seo-quick strong{display:block;font-size:13px}.tax-seo-quick span{display:block;margin-top:4px;color:#667085;font-size:11px}.tax-seo-side-title{padding:12px 12px 6px;font-size:11px;font-weight:700;color:#94a3b8}.tax-seo-side-link{display:flex!important;align-items:center;gap:10px;padding:10px 12px!important;margin:2px 6px;border-radius:10px;text-decoration:none;color:#e2e8f0!important;font-size:13px;font-weight:600}.tax-seo-side-link:hover{background:rgba(255,255,255,.08)}.tax-seo-panel{margin:0 0 18px;padding:20px;border:1px solid #dbe5f4;border-radius:14px;background:#fff}.tax-seo-panel h3{margin:0;color:#12356b;font-size:18px}.tax-seo-panel .hint{margin:6px 0 16px;color:#667085;font-size:12px;line-height:1.6}.tax-seo-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.tax-seo-field{display:flex;flex-direction:column;gap:6px}.tax-seo-field.full{grid-column:1/-1}.tax-seo-field label{font-size:13px;font-weight:600;color:#344054}.tax-seo-field input,.tax-seo-field textarea{width:100%;box-sizing:border-box;border:1px solid #d0d5dd;border-radius:9px;padding:10px 11px;font:inherit}.tax-seo-field textarea{min-height:90px}.tax-seo-save{margin-top:16px;border:0;border-radius:9px;padding:10px 18px;background:#2563eb;color:#fff;font-weight:700;cursor:pointer}.tax-seo-msg{margin-left:10px;font-size:12px;color:#166534}@media(max-width:700px){.tax-seo-quick,.tax-seo-form-grid{grid-template-columns:1fr}}';document.head.appendChild(s);}
  function buildQuickMenu(){if(document.querySelector('[data-tax-seo-quick-menu]'))return;var nav=document.querySelector('nav');if(!nav)return;var body=nav.querySelector('.flex.flex-1.flex-col.overflow-y-auto')||nav;var box=document.createElement('div');box.setAttribute('data-tax-seo-quick-menu','1');box.innerHTML='<div class="tax-seo-side-title">财税SEO</div>'+menu.map(function(item){return '<a class="tax-seo-side-link" href="'+item.href+'"><span style="width:22px;text-align:center">'+item.icon+'</span><span>'+item.text+'</span></a>';}).join('');body.insertBefore(box,body.firstChild);}
  function apiPanel(title,hint,endpoint,fields){if(!document.querySelector('#settings-content')||document.querySelector('[data-tax-seo-panel="'+endpoint+'"]'))return;var content=document.querySelector('#settings-content');var panel=document.createElement('div');panel.className='tax-seo-panel';panel.setAttribute('data-tax-seo-panel',endpoint);panel.innerHTML='<h3>'+title+'</h3><div class="hint">'+hint+'</div><form class="tax-seo-form-grid">'+fields.map(function(f){var control=f.type==='textarea'?'<textarea name="'+f.name+'" placeholder="'+esc(f.placeholder||'')+'"></textarea>':f.type==='checkbox'?'<input type="checkbox" name="'+f.name+'" style="width:auto;align-self:flex-start">':'<input name="'+f.name+'" type="'+(f.type||'text')+'" placeholder="'+esc(f.placeholder||'')+'">';return '<div class="tax-seo-field '+(f.full?'full':'')+'"><label>'+f.label+'</label>'+control+'</div>';}).join('')+'<div class="full"><button class="tax-seo-save" type="submit">保存设置</button><span class="tax-seo-msg"></span></div></form>';content.insertBefore(panel,content.firstChild);var form=panel.querySelector('form');fetch(endpoint,{credentials:'same-origin'}).then(function(r){return r.ok?r.json():null}).then(function(data){if(!data||!data.data)return;Object.keys(data.data).forEach(function(k){var el=form.elements[k];if(!el)return;if(el.type==='checkbox')el.checked=!!data.data[k];else el.value=data.data[k]||'';});}).catch(function(){});form.addEventListener('submit',function(ev){ev.preventDefault();var msg=panel.querySelector('.tax-seo-msg');msg.textContent='保存中…';var data={};Array.prototype.forEach.call(form.elements,function(el){if(!el.name)return;data[el.name]=el.type==='checkbox'?el.checked:el.value;});fetch(endpoint,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).then(function(r){return r.json().then(function(x){return {ok:r.ok};});}).then(function(x){msg.textContent=x.ok?'✓ 已保存':'保存失败';}).catch(function(){msg.textContent='保存失败';});});}
  function buildSeoAndLeadPanels(){if(!location.pathname.startsWith('/admin/settings/'))return;
    apiPanel('🏠 首页设置','前台首页标题与导航。','/admin/settings/api/home',[{name:'siteName',label:'站点名称',placeholder:'财税服务'},{name:'homeTitle',label:'首页大标题',full:true},{name:'homeIntro',label:'首页介绍',type:'textarea',full:true},{name:'homeNotice',label:'合规提示',type:'textarea',full:true},{name:'navHome',label:'导航·首页'},{name:'navNews',label:'导航·资讯'},{name:'navWechat',label:'导航·微信'},{name:'navContact',label:'导航·咨询'},{name:'navSearch',label:'导航·搜索'},{name:'showCities',label:'显示城市入口',type:'checkbox'},{name:'showNewsBlock',label:'显示资讯区块',type:'checkbox'},{name:'showWechatBlock',label:'显示微信区块',type:'checkbox'}]);
    apiPanel('🔎 SEO设置','传统搜索引擎 meta / robots / IndexNow。','/admin/settings/api/seo',[{name:'seoTitle',label:'网站标题',full:true},{name:'seoKeywords',label:'关键词'},{name:'canonicalUrl',label:'网站地址'},{name:'seoDescription',label:'网站描述',type:'textarea',full:true},{name:'robots',label:'Robots'},{name:'indexNowEnabled',label:'启用IndexNow',type:'checkbox'}]);
    apiPanel('🤖 AI关键词SEO','核心词 / 长尾词 / AI写作提示，用于内容生产与 meta keywords。','/admin/settings/api/ai-seo',[{name:'coreKeywords',label:'核心关键词（逗号分隔）',placeholder:'代理记账,代开发票,税务申报',full:true},{name:'longTailKeywords',label:'长尾关键词（每行一个）',type:'textarea',full:true,placeholder:'小微企业代理记账'},{name:'aiWritingPrompt',label:'AI写作提示词',type:'textarea',full:true},{name:'injectMetaKeywords',label:'注入meta keywords',type:'checkbox'}]);
    apiPanel('🌐 GEO设置','Generative Engine Optimization：给 ChatGPT / Perplexity 等 AI 引擎的结构化信息（JSON-LD）。','/admin/settings/api/geo',[{name:'enabled',label:'启用GEO结构化数据',type:'checkbox'},{name:'businessName',label:'业务名称',placeholder:'全国财税发票服务'},{name:'businessType',label:'业务类型',placeholder:'ProfessionalService'},{name:'serviceArea',label:'服务区域',placeholder:'中国全国主要城市'},{name:'city',label:'城市'},{name:'region',label:'省份'},{name:'country',label:'国家代码',placeholder:'CN'},{name:'address',label:'详细地址',full:true},{name:'telephone',label:'对外电话'},{name:'aiSummary',label:'AI可读业务说明',type:'textarea',full:true},{name:'faqPairs',label:'FAQ（问|答，每行一对）',type:'textarea',full:true}]);
    apiPanel('☎ 获客设置','前台右侧悬浮一键联系。','/admin/settings/api/lead',[{name:'contactPhone',label:'联系电话'},{name:'wechat',label:'微信号'},{name:'qq',label:'QQ号'},{name:'telegram',label:'Telegram'},{name:'whatsapp',label:'WhatsApp'},{name:'leadEnabled',label:'显示联系悬浮条',type:'checkbox'},{name:'leadMessage',label:'线索提示语',type:'textarea',full:true}]);
  }
  function buildHomePanel(){if(!(location.pathname==='/admin'||location.pathname==='/admin/content'))return;var main=document.querySelector('main');var content=main&&(main.querySelector('.grow')||main.lastElementChild);if(!content||content.querySelector('[data-tax-seo-shell]'))return;var shell=document.createElement('div');shell.setAttribute('data-tax-seo-shell','1');shell.innerHTML='<div class="tax-seo-brand"><div class="tax-seo-brand-icon">税</div><div><div class="tax-seo-brand-title">财税SEO</div><div class="tax-seo-brand-sub">内容 · 关键词 · GEO · 获客</div></div></div>';var quick=document.createElement('div');quick.className='tax-seo-quick';quick.innerHTML=menu.slice(0,10).map(function(item){return '<a href="'+item.href+'"><strong>'+item.icon+' '+item.text+'</strong><span>快捷入口</span></a>';}).join('');shell.appendChild(quick);content.insertBefore(shell,content.firstChild);}
  function buildPageShell(){if(!location.pathname.startsWith('/admin'))return;addStyles();buildQuickMenu();buildSeoAndLeadPanels();buildHomePanel();document.title='财税SEO管理后台';document.documentElement.lang='zh-CN';setText('Content','内容管理');setText('Users','客户管理');setText('Settings','系统设置');setText('Dashboard','数据概览');setText('Sign Out','退出登录');}
  function run(){buildPageShell();window.setTimeout(buildPageShell,300);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();
</script>`;
export function installBeginnerAdminUi(): void {
  const responseText = Response.prototype.text;
  if ((Response.prototype as Response & { __taxSeoPatched?: boolean }).__taxSeoPatched) return;
  const patched = async function (this: Response): Promise<string> {
    const text = await responseText.call(this);
    const type = this.headers.get('content-type') || '';
    if (!type.includes('text/html') || !text.includes('SonicJS')) return text;
    if (text.includes(MARKER)) return text;
    return text.includes('</body>') ? text.replace('</body>', script + '</body>') : text + script;
  };
  Response.prototype.text = patched;
  (Response.prototype as Response & { __taxSeoPatched?: boolean }).__taxSeoPatched = true;
}
installBeginnerAdminUi();
